# 配置数据库信息
spring:
datasource:
url: jdbc:mysql://10.10.65.174:3306/prctice2?useSSL=false&serverTimezone=UTC
username: root
password: Hongdou$2020
driver-class-name: com.mysql.cj.jdbc.Driver
web:
resources:
static-locations: classpath:/

# 配置mybatis 开启驼峰映射
mybatis-plus:
configuration:
map-underscore-to-camel-case: true